### ISSUE TITLE
Support for PHP 7.2

### ISSUE THREAD

**Issue by scottcdi** [yireo/Yireo_NewRelic#7]
Magento just recently announced that they will be openly supporting PHP 7.2 for the magento 1 instance and have also recently just released a patch.

Does anyone know if this plugin will be compatible with PHP 7.2 or if a patch is planning on being developed here as well?

**Comment by jissereitsma** [comment]
As far as I know, the module would theoretically run on PHP 7.2 just fine, because a lot of the codebase of 7.1 works the same under 7.2. Did you face any specific issues?

**Comment by scottcdi** [comment]
We are in the planning phase right now and have not spun up a dev env with the 7.2 upgrade to test if it works. If the base is set to 7.1, I don't foresee any problems but will post back here if we encounter any issues. Thank you. - scott
